# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fbdb5660db6cb2255aa25ad94c691fa800864753170cec39b6fc81288f66e0516915bbee78a3d127768abf22d3f8514d7fc911729d24a283a2a8238a3b2c5c5

test:
  secret_key_base: 80aa4e4ece58772082d7cfe84e8071ef5f100686ad59720494b9801f43a6177779690c8f3a36e893d6cdc94618d71b3d02aa9ebeecaa0b78e2467107ba2df77c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
